### PR TITLE
plotly.js fix bug when crosstalk filter keys are null

### PR DESCRIPTION
**Pull request by casperhart**
Hi, this is my first PR to this repository and I have reviewed the contributing guidelines. However I wasn't sure if it was necessary to create an issue first, or how to write tests for this change, so I'm open to suggestions.

## Why this PR?

I was having an issue using plotly with crosstalk filtering, where if all filters were cleared, the filtering would not be removed correctly and an exception would be raised in the browser console. This PR fixes that issue.

## Example

```r
library(crosstalk)
library(plotly)
library(DT)

data(iris)

shared_iris <- SharedData$new(iris)

a <- plot_ly(shared_iris, x = ~Sepal.Length, y = ~Sepal.Width) %>%
    add_markers() %>%
    highlight(on = "plotly_click", dynamic = TRUE)
b <- datatable(shared_iris)

bscols(
    list(
        filter_checkbox("species", "Species", shared_iris, ~Species)
    ),
    a, b 
)
```

### Steps to reproduce

In the webpage generated by the above code, select `setosa` under the species checkbox filter. Then unselect `setosa`

### Expected behaviour

the filtering returns to its original state

### Actual behaviour

the filtering doesn't change, and the following error appears in the console:
image

### CODE REVIEW

**Comment by tbrittoborges** [comment]
@casperhart maybe this relates with https://github.com/rstudio/crosstalk/issues/124 ?

**Comment by casperhart** [comment]
> @casperhart maybe this relates with [rstudio/crosstalk#124](https://github.com/rstudio/crosstalk/issues/124) ?

Running the code in the issue you linked, I didn't see any errors or anything so probably not the same bug

**Comment by cpsievert** [comment]
Thanks @casperhart (and sorry for the wait)! This looks good, would you mind also updating the `NEWS.md` to mention this fix under the "Bug Fixes" section?

**Comment by casperhart** [comment]
@cpsievert I've now updated `News.md`. On a different note, can you please also take a look at #2098? It's a similar issue relating to `{crosstalk}`

**Pull request merged**
