### PR TITLE
Closes #1872. Implemented to_basic for `geom_function`

### LINKED ISSUE #1872: geom/stat_function no longer supported
I used to be able to run the following code to render the plot containing stat_function() interactive (it was actually used with renderPlotly in a shiny app, but I tried to keep it simple and reproductible) before updating to the latest versions of R Studio and Plotly:

```r
p <- ggplot(data = data.frame(x = 0), mapping = aes(x = x)) + 
  stat_function(fun = function(x) x^2+3) + 
  stat_function(fun = function(x) 5) + 
  xlim(1, 5)

ggplotly(p)

```

Now it throws the error `1: In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomFunction() has yet to be implemented in plotly.`.

### PR DESCRIPTION
**Pull request by moutikabdessabour**
@cpsievert Implemented `to_basic` for `GeomFunction` class.

### CODE REVIEW

**Comment by moutikabdessabour** [comment]
@cpsievert by test do you mean just running `ggplotly(p)` without the error being thrown or a visual test?

**Comment by cpsievert** [comment]
A visual test (`expect_doppelganger()`)

**Comment by cpsievert** [comment]
There are lots of examples under `test/testthat`, for example https://github.com/plotly/plotly.R/blob/master/tests/testthat/test-plotly-area.R

**Comment by moutikabdessabour** [comment]
@cpsievert thanks I found the function in `helpers-vdiff` and was able to understand the way it functions. I added two unit tests.

**Pull request merged**
