### PR TITLE
Fix "partial argument match" warnings (#1977)

### PR DESCRIPTION
**Pull request by bersbersbers**
For the first version of this PR, I am most of all interested in if/how CI works.

I will then fix more of these warnings in later commits.

Finally, I wonder how tests should be adapted for this case. On my system, with `options(warnPartialMatchArgs = TRUE)` in `.Rprofile`, several existing tests are issuing warnings. One could use
```r
options(warnPartialMatchArgs = TRUE, warnPartialMatchAttr = TRUE, warnPartialMatchDollar = TRUE)
```
in the setup of any test, but that might fail if dependencies issue such warnings.

### CODE REVIEW

**Comment by moutikabdessabour** [comment]
@bersbersbers Thanks for the time you put on this. For the tests you can try calling dev_fun directly and use something like `expect_failure(expect_warning(dev_fun))`. And Only set the `options` inside the test scope. this looks good to me. I'm waiting for @cpsievert to give me the green light to merge.

**Comment by bersbersbers** [comment]
> Please update `NEWS.md` accordingly

@cpsievert thanks - done!

**Comment by bersbersbers** [comment]
@moutikabdessabour done :)

**Comment by moutikabdessabour** [comment]
@bersbersbers can you please use rebase instead of the cmerge master commit". Once it's done I will merge the PR. Again thanks for your time and effort.

**Comment by bersbersbers** [comment]
@moutikabdessabour I did it :)

**Pull request merged**
